// <auto-generated />
using System;
using GFS.QuotesService.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GFS.QuotesService.DAL.Migrations
{
    [DbContext(typeof(QuotesServiceDbContext))]
    [Migration("20221113195423_RenameHiToHigh")]
    partial class RenameHiToHigh
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GFS.QuotesService.DAL.Entities.AssetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssetType")
                        .HasColumnType("integer");

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FIGI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ISIN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MarketType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("GFS.QuotesService.DAL.Entities.AssetInfoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<DateTime?>("IpoDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Lot")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MinPriceIncrement")
                        .HasColumnType("numeric");

                    b.Property<string>("Sector")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.ToTable("AssetInfos", (string)null);
                });

            modelBuilder.Entity("GFS.QuotesService.DAL.Entities.BackgroundWorkerTaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuotesProviderAssetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuotesProviderAssetId");

                    b.ToTable("BackgroundWorkerTasks", (string)null);
                });

            modelBuilder.Entity("GFS.QuotesService.DAL.Entities.QuoteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric");

                    b.Property<Guid>("QuotesProviderAssetId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimeFrame")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("QuotesProviderAssetId", "TimeFrame");

                    b.HasIndex("QuotesProviderAssetId", "TimeFrame", "Date")
                        .IsUnique();

                    b.ToTable("Quotes", (string)null);
                });

            modelBuilder.Entity("GFS.QuotesService.DAL.Entities.QuotesProviderAssetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuotesProviderType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("QuotesProviderAssets", (string)null);
                });

            modelBuilder.Entity("GFS.QuotesService.DAL.Entities.AssetInfoEntity", b =>
                {
                    b.HasOne("GFS.QuotesService.DAL.Entities.AssetEntity", "Asset")
                        .WithOne("AssetInfo")
                        .HasForeignKey("GFS.QuotesService.DAL.Entities.AssetInfoEntity", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("GFS.QuotesService.DAL.Entities.BackgroundWorkerTaskEntity", b =>
                {
                    b.HasOne("GFS.QuotesService.DAL.Entities.QuotesProviderAssetEntity", "QuotesProviderAsset")
                        .WithMany("BackgroundWorkerTasks")
                        .HasForeignKey("QuotesProviderAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuotesProviderAsset");
                });

            modelBuilder.Entity("GFS.QuotesService.DAL.Entities.QuoteEntity", b =>
                {
                    b.HasOne("GFS.QuotesService.DAL.Entities.QuotesProviderAssetEntity", "QuotesProviderAsset")
                        .WithMany("Quotes")
                        .HasForeignKey("QuotesProviderAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuotesProviderAsset");
                });

            modelBuilder.Entity("GFS.QuotesService.DAL.Entities.QuotesProviderAssetEntity", b =>
                {
                    b.HasOne("GFS.QuotesService.DAL.Entities.AssetEntity", "Asset")
                        .WithMany("QuotesProviderAssets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("GFS.QuotesService.DAL.Entities.AssetEntity", b =>
                {
                    b.Navigation("AssetInfo");

                    b.Navigation("QuotesProviderAssets");
                });

            modelBuilder.Entity("GFS.QuotesService.DAL.Entities.QuotesProviderAssetEntity", b =>
                {
                    b.Navigation("BackgroundWorkerTasks");

                    b.Navigation("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
